<?php

namespace Objects\InternJumpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DayActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayActivityRepository extends EntityRepository {

    /**
     * get activities
     * @author ahmed
     * @param datetime $from
     * @param datetime $to
     */
    public function getActivites($from, $to) {
        return $this->getEntityManager()->createQuery("
            select da FROM ObjectsInternJumpBundle:DayActivity da
            where da.createdAt >= :from and da.createdAt <= :to
            ")->setParameters(array('from' => $from, 'to' => $to))->getResult();
    }

}