<?php

namespace Objects\InternJumpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EducationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationRepository extends EntityRepository {

    /**
     * This is for getting all user's Education
     * @author Ola
     * @param type $uid User Id
     * @return null
     */
    public function getAllEducation($uid) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT e
            FROM ObjectsInternJumpBundle:Education e
            JOIN e.user u
            WHERE u.id = :uid
            ')->setParameter('uid', $uid);
        return $query->getResult();
    }

}