<?php

namespace Objects\InternJumpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestRepository extends EntityRepository {

    /**
     * this function is used to get the students objects that the company can send messages to
     * the main use in CompanyMessageController:getValidUsersToSendTo
     * @author Mahmoud
     * @param integer $companyId
     * @return array
     */
    public function getCompanyAcceptedInterests($companyId) {
        $query = $this->getEntityManager()->createQuery("
            SELECT DISTINCT u, i
            FROM ObjectsInternJumpBundle:Interest i
            JOIN i.company c
            JOIN i.user u
            WHERE c.id = :companyId
            AND i.accepted = 'accepted'
            ")->setParameter('companyId', $companyId);
        return $query->getResult();
    }

    /**
     * this function is used to get the companies objects that the user can send messages to
     * the main use in UserMessageController:getValidCompaniesToSendTo
     * @author Mahmoud
     * @param integer $userId
     * @return array
     */
    public function getCompanyInterests($userId) {
        $query = $this->getEntityManager()->createQuery("
            SELECT DISTINCT c, i
            FROM ObjectsInternJumpBundle:Interest i
            JOIN i.company c
            JOIN i.user u
            WHERE u.id = :userId
            ")->setParameter('userId', $userId);
        return $query->getResult();
    }

}