<?php

namespace Objects\InternJumpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InternshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternshipRepository extends EntityRepository {

    /**
     * this function used to get relted jobs to job categories
     * @author ahmed
     * @param int $id
     * @param int $jobCatIds
     */
    public function getRelatedJobs($jobId, $jobCatIds) {
        $query = $this->getEntityManager()->createQuery('
            SELECT i
            FROM ObjectsInternJumpBundle:Internship i
            JOIN i.categories c
            WHERE i.id != :jobId
            and c.id in (:jobCatIds)
            and i.active = true
            AND  i.activeFrom <= :today
            AND  i.activeTo >= :today
            order by i.createdAt desc
            ')->setParameters(array('today' => new \DateTime(), 'jobId' => $jobId, 'jobCatIds' => $jobCatIds))->setMaxResults(5);
        return $query->getResult();
    }

    /**
     * get recent jobs
     * @author ahmed
     * @param int $max
     * @return type
     */
    public function getRecentJobs($max) {
        $query = $this->getEntityManager()->createQuery('
            SELECT i
            FROM ObjectsInternJumpBundle:Internship i
            WHERE i.active = true
            AND  i.activeFrom <= :today
            AND  i.activeTo >= :today
            order by i.createdAt desc
            ')->setParameters(array('today' => new \DateTime()))->setMaxResults($max);
        return $query->getResult();
    }

    /**
     * get all job categories ids
     * @author ahmed
     * @param int $jobId
     * @return type
     */
    public function getJobCatIds($jobId) {
        $query = $this->getEntityManager()->createQuery('
            SELECT c.id
            FROM ObjectsInternJumpBundle:Internship i
            JOIN i.categories c
            WHERE i.id = :jobId
            ')->setParameter('jobId', $jobId);
        $result = $query->getResult();
        $ids = array();
        if (count($result) > 0) {
            foreach ($result as $idArray) {
                $ids [] = $idArray['id'];
            }
        }
        return $ids;
    }

    /**
     * this function get jobs mathching to user
     * @author ahmed
     * @param string $userCvCategoriesIds
     * @param string $country
     * @param string $state
     */
    public function getmatchingUserJobs($userCvCategoriesIds, $country, $state) {
        ;
        $parameters = array('today' => new \DateTime(date('Y-m-d')));
        $query = '
            SELECT j
            FROM ObjectsInternJumpBundle:Internship j
            JOIN j.categories c
            WHERE j.active = true and j.createdAt = :today
            ';

        if ($userCvCategoriesIds) {
            $query .= ' and c.id in (:userCvCategoriesIds)';
            $parameters ['userCvCategoriesIds'] = $userCvCategoriesIds;
        }

        if ($country) {
            $query .= ' and j.country = :country';
            $parameters ['country'] = $country;
        }

        if ($state) {
            $query .= ' and j.state = :state';
            $parameters ['state'] = $state;
        }

        $query = $this->getEntityManager()
                        ->createQuery($query)->setParameters($parameters);

        return $query->getResult();
    }

    /**
     * this function is used to get the company jobs categories ids
     * the main use in CompanyController:searchForCVAction
     * @author Mahmoud
     * @param integer $companyId
     * @return array
     */
    public function getCompanyCategoriesIds($companyId) {
        $query = $this->getEntityManager()->createQuery('
            SELECT DISTINCT ca.id
            FROM ObjectsInternJumpBundle:Internship i
            JOIN i.categories ca
            JOIN i.company c
            WHERE c.id = :companyId
            ')->setParameter('companyId', $companyId);
        $result = $query->getResult();
        $ids = array();
        if (count($result) > 0) {
            foreach ($result as $idArray) {
                $ids [] = $idArray['id'];
            }
        }
        return $ids;
    }

    /**
     * this fuction used to get hired users for company
     * @author Ahmed
     * @param int $jobsId
     */
    public function getCompanyHiredUsers($jobsId) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT ui
            FROM ObjectsInternJumpBundle:UserInternship ui
            JOIN ui.internship i
            WHERE i.id in (:jobsId) and ui.status = :status
            ')->setParameters(array('jobsId' => $jobsId, 'status' => 'accepted'));
        return $query->getResult();
    }

    /**
     * this function will get all company jobs ids
     * @author Ahmed
     * @param int $companyId
     */
    public function getCompanyJobsIds($companyId) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT j.id
            FROM ObjectsInternJumpBundle:Internship j
            JOIN j.company c
            WHERE c.id = :companyId
            ')->setParameters(array('companyId' => $companyId));
        return $query->getResult();
    }

    /**
     * this function will get company jobs except one
     * @author Ahmed
     * @param int $id
     * @param int $companyId
     */
    public function getOtherJobs($id, $companyId) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT j
            FROM ObjectsInternJumpBundle:Internship j
            JOIN j.company c
            WHERE c.id = :companyId and j.id != :id
            ORDER BY j.createdAt DESC
            ')->setParameters(array('companyId' => $companyId, 'id' => $id));
        return $query->getResult();
    }

    /**
     * this function will get latest internships
     * @author Ahmed
     * @param int $maxResults
     */
    public function getLatestinternShips($maxResults) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT j
            FROM ObjectsInternJumpBundle:Internship j
            WHERE j.active = true and j.activeTo >= :todayDate
            ORDER BY j.createdAt DESC
            ')->setMaxResults($maxResults)->setParameter('todayDate', new \DateTime());
        return $query->getResult();
    }

    /**
     * this function will get all company jobs by company id
     * @author Ahmed
     * @param int $companyId
     */
    public function getAllCompanyJobs($companyId) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT j
            FROM ObjectsInternJumpBundle:Internship j
            JOIN j.company c
            WHERE c.id = :companyId and j.active = true
            ORDER BY j.createdAt DESC
            ')->setParameters(array('companyId' => $companyId));
        return $query->getResult();
    }

    /**
     * this function will get company jobs by company id
     * @author Ahmed
     * use InternshipController:indexAction
     * @param int $companyId
     * @param int $page
     * @param int $itemsPerPage
     */
    public function getCompanyJobs($companyId, $page, $itemsPerPage, $owner) {
        if ($page < 1) {
            return array();
        }
        $page--;
        $parameters ['companyId'] = $companyId;
        $query = '
            SELECT j
            FROM ObjectsInternJumpBundle:Internship j
            JOIN j.company c
            WHERE c.id = :companyId
            ';

        if (!$owner) {
            $query .= ' and j.active = true and j.activeFrom <= :todayDate and j.activeTo >= :todayDate';
            $parameters ['todayDate'] = new \DateTime('today');
        }

        $query .= ' ORDER BY j.createdAt DESC';
        $query = $this->getEntityManager()
                ->createQuery($query);

        $query->setParameters($parameters);
        if ($itemsPerPage) {
            $query->setFirstResult($page * $itemsPerPage);
            $query->setMaxResults($itemsPerPage);
        }
        return $query->getResult();
    }

    /**
     * this function will get all company jobs count
     * second use in CompanyController:companyPublicProfileAction
     * @author Ahmed
     * @param int $companyId
     */
    public function countCompanyJobs($companyId, $owner) {
        $parameters ['companyId'] = $companyId;
        $query = '
            SELECT count(j.id) as jobsCount
            FROM ObjectsInternJumpBundle:Internship j
            JOIN j.company c
            WHERE c.id = :companyId
            ';
        if (!$owner) {
            $query .= ' and j.active = true and j.activeFrom <= :todayDate and j.activeTo >= :todayDate';
            $parameters ['todayDate'] = new \DateTime('today');
        }
        $query = $this->getEntityManager()
                ->createQuery($query);

        $query->setParameters($parameters);
        return $query->getResult();
    }

    /**
     * to get all the accepted users in a certain Company
     * @author Ola
     * @param type $id
     * @return type
     */
    public function getAllCompanyUsers($companyId) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT ui
            FROM ObjectsInternJumpBundle:UserInternship ui
            JOIN ui.internship j
            JOIN j.company c
            WHERE c.id = :cId
            AND ui.status = :status
            ORDER BY j.title
            ')->setParameters(array('cId' => $companyId, 'status' => 'accepted'));
        return $query->getResult();
    }

    /**
     * this function used to get latest hired users
     * @author ahmed
     * @param integer $maxResults
     */
    public function getLatestHiredUsers($maxResults) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT ui
            FROM ObjectsInternJumpBundle:UserInternship ui
            WHERE ui.status = :status
            ORDER BY ui.createdAt desc
            ')->setParameters(array('status' => 'accepted'));
        return $query->getResult();
    }

    /**
     * this function will get all Latest jobs according to certain cv categories
     * @author Ola
     * @param type $categories
     * @return array of jobs
     */
    public function getLatestJobs($categories, $limit) {

        $date = new \DateTime("today");
        $today = $date->format('Y-m-d');
        $query = $this->getEntityManager()
                ->createQuery('
            SELECT  DISTINCT j
            FROM ObjectsInternJumpBundle:Internship j
            JOIN j.company c
            JOIN j.categories cat
            WHERE j.active = true
            AND  j.activeFrom <= :today
            AND  j.activeTo >= :today
            AND cat.id IN (:categories)
            ORDER BY j.createdAt DESC
            ');
        $query->setParameters(array('today' => $today, 'categories' => $categories));
        $query->setMaxResults($limit);
        return $query->getResult();
    }

    /**
     * this function will get all jobs search results according to sent parameters
     * @author Ola
     * @param string $title
     * @param string $country
     * @param string $city
     * @param string $state
     * @param int $category
     * @param string $company
     * @param int $page
     * @return array of jobs
     */
    public function getJobsSearchResult($title, $country, $city, $state, $category, $company, $lang, $keywordsArray, $jobType, $page, $jobsPerPage) {
//print_r($keywordsArray);exit;
        if ($page < 1) {
            return array();
        }
        $page--;

        $today = new \DateTime("today");

        $para = array();
        $para['today'] = $today;
        $query = '
            SELECT  j, c
            FROM ObjectsInternJumpBundle:Internship j
            JOIN j.company c
            JOIN j.categories cat
            LEFT JOIN j.keywords kw
            JOIN j.languages il
            JOIN il.language l
            WHERE j.active = true AND  j.activeFrom <= :today AND  j.activeTo >= :today
            ';
        //j.id,j.title,j.description, j.position, j.createdAt, j.activeFrom, j.activeTo, j.country, c.id AS companyId, c.name AS companyName
        if ($title != 'empty') {
            $query .= ' AND (j.title LIKE :title OR  j.description LIKE :title OR kw.name IN (:keywords) ) '; // OR j.position LIKE :title
            $para ['title'] = "%" . $title . "%";
            $para ['keywords'] = $keywordsArray;
        }
        if ($country != 'empty') {
            $query .= ' AND j.country = :country';
            $para ['country'] = $country;
        }
        if ($city != 'empty') {
            $query .= ' AND j.city = :city';
            $para ['city'] = $city;
        }
        if ($state != 'empty') {
            $query .= ' AND j.state = :state';
            $para ['state'] = $state;
        }
        if ($category != 'empty') {
            $query .= ' AND cat.id = :category';
            $para ['category'] = $category;
        }
        if ($company != 'empty') {
            $query .= ' AND c.id = :company';
            $para ['company'] = $company;
        }
        if ($lang != 'empty') {
            $query .= ' AND l = :lang';
            $para ['lang'] = $lang;
        }
        if ($jobType != 'empty') {
            $query .= ' AND j.positionType = :jobtype';
            $para ['jobtype'] = $jobType;
        }
//print_r($query);exit;
        $query .= ' GROUP BY j.id  ORDER BY j.createdAt DESC';

        $query = $this->getEntityManager()->createQuery($query);
        $query->setParameters($para);

        if ($jobsPerPage) {
            $query->setFirstResult($page * $jobsPerPage);
            $query->setMaxResults($jobsPerPage);
        }

        return $query->getResult();
    }

    /**
     * this function will count all jobs search results according to sent parameters
     * @author Ola
     * @param string $title
     * @param string $country
     * @param string $city
     * @param string $state
     * @param int $category
     * @param string $company
     * @return array of jobs
     */
    public function countAllJobsSearchResults($title, $country, $city, $state, $category, $company) {

        $para = array();
        $query = '
            SELECT  COUNT(j.id) AS jobsCount
            FROM ObjectsInternJumpBundle:Internship j
            JOIN j.company c
            JOIN j.categories cat
            WHERE j.active = true
            ';
        if ($title != 'empty') {
            $query .= ' and j.title LIKE :title OR j.description LIKE :title'; // OR j.position LIKE :title
            $para ['title'] = "%" . $title . "%";
        }
        if ($country != 'empty') {
            $query .= ' AND j.country = :country';
            $para ['country'] = $country;
        }
        if ($city != 'empty') {
            $query .= ' AND j.city = :city';
            $para ['city'] = $city;
        }
        if ($state != 'empty') {
            $query .= ' AND j.state = :state';
            $para ['state'] = $state;
        }
        if ($category != 'empty') {
            $query .= ' AND cat.id = :category';
            $para ['category'] = $category;
        }
        if ($company != 'empty') {
            $query .= ' AND c.id = :company';
            $para ['company'] = $company;
        }

//        $query .= ' GROUP BY j.id ORDER BY j.createdAt DESC';
        $query = $this->getEntityManager()->createQuery($query);
        $query->setParameters($para);

        $result = $query->getResult();
        return $result;
        if ($result)
            return $result['0']['jobsCount'];
        else
            return $result;
    }

}