<?php

namespace Objects\InternJumpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MajorSalaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MajorSalaryRepository extends EntityRepository {

    /**
     * this fuction used to get skill by name
     * @author Ahmed
     * @param string $name
     */
    public function getMajorObject($name) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT m
            FROM ObjectsInternJumpBundle:MajorSalary m
            WHERE m.name like :name
            ')->setParameter('name', "$name%")->setMaxResults(1);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}