<?php

namespace Objects\InternJumpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * this is to get all published posts 
     * @author Ola
     * @param type $page
     * @param type $itemsPerPage
     * @return array
     */
    public function getAllPosts($page, $itemsPerPage) {

        if ($page < 1) {
            return array();
        }
        $page--;

        $query = $this->getEntityManager()
                    ->createQuery('
                        SELECT p 
                        FROM ObjectsInternJumpBundle:Post p 
                        ORDER BY p.createdAt DESC
                     ');


        if ($itemsPerPage) {
            $query->setFirstResult($page * $itemsPerPage);
            $query->setMaxResults($itemsPerPage);
        }

        $result = $query->getResult();
        return $result;
    }

    /**
     * this is to count all published posts
     * @author Ola
     * @return integer
     */
    public function countAllPosts() {

        $query = $this->getEntityManager()
                    ->createQuery('
                        SELECT count(p.id) as postsCount 
                        FROM ObjectsInternJumpBundle:Post p
                    ');

        $result = $query->getResult();
        
        if ($result)
            return $result['0']['postsCount'];
        else
            return $result;
    }
            
}