<?php

namespace Objects\InternJumpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends EntityRepository
{
    /**
     * this function will delete all states
     */
    public function deleteAll() {
        $query = $this->getEntityManager()
                ->createQuery("
                     DELETE ObjectsInternJumpBundle:State s
                    ");
        $query->execute();
    }
}