<?php

namespace Objects\InternJumpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TopUniversityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopUniversityRepository extends EntityRepository {

    /**
     * this fuction used to get university by name
     * @author Ahmed
     * @param string $name
     */
    public function getUniversityObject($name) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT u
            FROM ObjectsInternJumpBundle:TopUniversity u
            WHERE u.name like :name
            ')->setParameter('name', "$name%")->setMaxResults(1);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}