services:
    validator.unique.globalunique:
        class: Objects\InternJumpBundle\Validator\Constrains\GlobalUniqueValidator
        arguments: [@doctrine]
        tags:
            - { name: validator.constraint_validator, alias: objectsunique }
