imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: "../../src/Objects/InternJumpBundle/Resources/config/config.yml" }
    - { resource: "../../src/Objects/InternJumpBundle/Resources/config/configSiteForms.yml" }

framework:
    esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        refresh_notification_time: %refresh_notification_time%
        site_meta_title: %site_meta_title%
        site_meta_keywords: %site_meta_keywords%
        site_meta_description: %site_meta_description%
        face_page_url: %face_page_url%
        twitter_page_url: %twitter_page_url%
        google_page_url: %google_page_url%
        linkledIn_page_url: %linkledIn_page_url%
        analytics: %analytics%
        facebook_mesasage: %facebook_mesasage%
        internjumb_copyright: %internjumb_copyright%
        contact_info_name: %contact_info_name%
        contact_info_address_part1: %contact_info_address_part1%
        contact_info_address_part2: %contact_info_address_part2%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: false
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# Sonata Configuration
sonata_admin:
    title:      internjump Admin
    title_logo: /apple-touch-icon.png
    templates:
        # default global templates
        layout: ObjectsAdminBundle:Admin:standard_layout.html.twig
        edit: ObjectsAdminBundle:Admin:standard_edit_layout.html.twig

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list, settings: { groups: [user] } }
            - { position: right, type: sonata.admin.block.admin_list, settings: { groups: [company] } }
            - { position: right, type: sonata.admin.block.admin_list, settings: { groups: [General] } }

        groups:
            user:
                items:
                    - user_admin
                    - cv_category_admin
                    - skill_admin
                    - quiz_admin
                    - quiz_result_admin
                    - personal_question_admin
                    - cv_admin
            company:
                items:
                    - company_admin
                    - company_question_admin
                    - internship_admin
            General:
                items:
                    - founder_admin
                    - FAQ_admin
                    - post_admin
                    - post_category_admin
                    - languages_admin
                    - worth_admin
                    - report_admin
                    - banner_admin

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

#services:
#    kernel.listener.InternJumpRequestListener:
#        class: Objects\InternJumpBundle\EventListener\InternJumpRequestListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onRequest }
#        arguments: [ @service_container, @security.context]