# Internal routing configuration to handle ESI
_internal:
   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
   prefix:   /_internal

# admin urls
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# extra route to point to the same /admin/dashboard route without the dashboard
admin_home:
    pattern:  /admin
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

# Bundles routes
ObjectsAdminBundle:
    resource: "@ObjectsAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
ObjectsAPIBundle:
    resource: "@ObjectsAPIBundle/Resources/config/routing.yml"
    prefix:   /

ObjectsUserBundle:
    resource: "@ObjectsUserBundle/Resources/config/routing.yml"
    prefix:   /

ObjectsInternJumpBundle:
    resource: "@ObjectsInternJumpBundle/Resources/config/routing.yml"
    prefix:   /

