security:
    encoders:
        Objects\UserBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
        Objects\InternJumpBundle\Entity\Company:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
        Objects\InternJumpBundle\Entity\Manager:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_COMPANY:     ROLE_NOTACTIVE_COMPANY
        ROLE_USER:        ROLE_NOTACTIVE
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            providers: [company, manager, user]
        company:
            entity: { class: Objects\InternJumpBundle\Entity\Company, property: loginName }
        user:
            entity: { class: Objects\UserBundle\Entity\User }
        manager:
            entity: { class: Objects\InternJumpBundle\Entity\Manager, property: loginName }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            provider: main
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
                always_use_default_target_path: true
                use_forward: true
                default_target_path: /user/auth/redirect/user

            logout:
                path:   /logout
                target: /

            remember_me:
                key:      "%secret%"
                # the next lifetime is in seconds (7days) max 86391359
                lifetime: 604800
                path:     /

    access_control:
#         - { path: ^/, requires_channel: https }
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/user/auth/redirect/user$, roles: [ROLE_NOTACTIVE, ROLE_NOTACTIVE_COMPANY, ROLE_ACTIVE_SOCIAL, ROLE_NOTACTIVE_SOCIAL, ROLE_COMPANY_MANAGER] }
         - { path: ^/company/messages, roles: [ROLE_COMPANY, ROLE_COMPANY_MANAGER] }
#         - { path: ^/user/messages, roles: ROLE_USER }
         - { path: ^/user/signup/second/step, roles: [ROLE_ACTIVE_SOCIAL, ROLE_NOTACTIVE_SOCIAL] }
#         - { path: ^/user/signup/third/step, roles: ROLE_NOTACTIVE }
#         - { path: ^/user/signup/fourth/step, roles: ROLE_NOTACTIVE }
#         - { path: ^/cv, roles: ROLE_NOTACTIVE }
         - { path: ^/search-for-cv, roles: ROLE_COMPANY }
#         - { path: ^/education, roles: ROLE_NOTACTIVE }
#         - { path: ^/employmenthistory, roles: ROLE_NOTACTIVE }
#         - { path: ^/user/auth, roles: ROLE_NOTACTIVE }
         - { path: ^/user/auth/active, roles: ROLE_USER }
         - { path: ^/user/auth/fully, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
#        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
