<?php

/**
 * @author ahmed
 */

namespace Objects\UserBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Objects\InternJumpBundle\Entity\Skill;

class InternjumpData implements FixtureInterface {

    public function load(ObjectManager $manager) {
        //skills array
        $skillsArray = array(
            "Windows OS",
            "Mac OS",
            "Solaris",
            "Unix",
            "Linux",
            "Sun OS",
            "OS/2",
            "Novell",
            "Microsoft Office",
            "MS Word",
            "Access",
            "Excel",
            "MS Frontpage",
            "MS Visio",
            "MS Siteserver",
            "Outlook",
            "Powerpoint",
            "Adobe Photoshop",
            "Adobe Illustrator",
            "Corel Draw Pro",
            "Corel Coffee Cup",
            "Quark Xpress",
            "Homesite",
            "Coldfusion",
            "Studio",
            "Dreamweaver",
            "Inspiration",
            "Filemaker",
            "SQL Server",
            "Mysql",
            "Enterprise Manager",
            "Linkbot",
            "Astra Site Manager",
            "Netobjects Fusion",
            "Broadvision",
            "Vignette",
            "Pandesic",
            "Websphere",
            "Eshare",
            "LivePerson",
            "Borland sidekick",
            "Game Design",
            "Game Programming",
            "Lacerte",
            "Scheduler",
            "Autocad",
            "Oracle",
            "Ajax",
            "able to work under pressure",
            "able to multi-task",
            "Data Analysis",
            "Animation",
            "American sign language",
            "Mandarin",
            "Spanish",
            "Castilian",
            "English",
            "Hindi",
            "Urdu",
            "Arabic",
            "Bengali",
            "Portuguese",
            "Russian",
            "Japanese",
            "Punjabi",
            "German",
            "Wu",
            "Telugu",
            "Vietnamese",
            "Marathi",
            "French",
            "Korean",
            "Tamil",
            "Cantonese",
            "Turkish",
            "Pashto",
            "Italian",
            "Mathematica",
            "Min Nan",
            "Taiwanese",
            "Gujarati",
            "Polish",
            "Persian",
            "Bhojpuri",
            "Awadhi",
            "Ukrainian",
            "Malay",
            "Xiang",
            "Malayalam",
            "Kannada",
            "Maithili",
            "Sundanese",
            "Burmese",
            "Oriya",
            "Marwari",
            "Hakka",
            "Thai",
            "Hausa",
            "Tagalog",
            "Filipino",
            "Romanian",
            "Dutch",
            "Gan",
            "Sindhi",
            "Uzbek",
            "Azerbaijani",
            "Rajasthani",
            "Yoruba",
            "Igbo",
            "Northern Berber",
            "Amharic",
            "Oromo",
            "Chhattisgarhi",
            "Assamese",
            "Kurdish",
            "Serbo-Croatian",
            "Bosnian-Croatian-Serbian",
            "Sinhalese",
            "Cebuano",
            "Rangpuri",
            "Malagasy",
            "Khmer",
            "Zhuang",
            "Nepali",
            "Rwanda-Rundi",
            "Somali",
            "Madurese",
            "Haryanvi",
            "Fula",
            "Bavarian",
            "Magahi",
            "Greek",
            "Chittagonian",
            "Deccan",
            "Hungarian",
            "Catalan",
            "Bulgarian-Macedonian",
            "Shona",
            "Objective C",
            "Min Bei",
            "Zulu",
            "Sylheti",
            "Czech",
            "Min Dong",
            "Lombard",
            "Uyghur",
            "Chewa",
            "Belarusian",
            "Kazakh",
            "Swedish",
            "Akan",
            "Makuwa",
            "Tatar-Bashkir",
            "Xhosa",
            "Haitian",
            "Albanian",
            "Gikuyu",
            "Neapolitan",
            "Ilokano",
            "Balochi",
            "Southern Quechua",
            "Batak",
            "Turkmen",
            "Mossi-Dagomba",
            "Armenian",
            "Sukuma-Nyamwezi",
            "Tshiluba",
            "Santali",
            "Venetian",
            "Kongo",
            "Hiligaynon",
            "Tigrinya",
            "Mongolian",
            "Bhili",
            "Danish",
            "Minangkabau",
            "Kashmiri",
            "Hebrew",
            "Finnish",
            "Slovak",
            "Afrikaans",
            "Guarani",
            "Mandingo",
            "Sicilian",
            "Norwegian",
            "Lithuanian",
            "Advertising",
            "Account Management",
            "Budgeting",
            "Blogging",
            "Team Building",
            "Banking",
            "Business Analysis",
            "Biotechnology",
            "Biology",
            "Biometrics",
            "Biostatistics",
            "Molecular Biology",
            "Cell Biology",
            "Biochemistry",
            "Biomedical engineering",
            "Contract Negotiation",
            "Construction",
            "Conflict Resolution",
            "E-commerce",
            "Editing",
            "Film",
            "Financial Analysis",
            "Final Cut Pro",
            "Final Draft",
            "Flash",
            "Html",
            "VBA",
            "C++",
            "Java",
            "Matlab",
            "Indesign",
            "J2EE",
            "Javascript",
            "Mergers and Acquisitions",
            "Photography",
            "PHP",
            "C#",
            "C",
            "Ruby",
            "Ruby on Rails",
            "Pyton",
            "VB.net",
            "Marketing",
            "Perl",
            "Quickbooks",
            "Research",
            "Risk Management",
            "SEO",
            "Social Media",
            "TCP/IP",
            "UM",
            "VMware",
            "Visual Basic",
            "Visio",
            "Web Design",
            "Wordpress",
            "Web 2.0",
            "XML",
            "XSL",
            "Xilinx",
            "XSD",
            "Youtube",
            "Yoga",
            "Zbrush",
            "Communication Skills",
            "Strong Writing Skills",
            "Strong Oral Communication",
            "Financial Modeling",
            "Accounting",
            "Bloomberg",
            "Factset",
            "QADirect",
            "Sybase",
            "Database Modeling Skills",
            "Computer Science",
            "Math",
            "Calculus",
            ".NET",
            "GUI Development",
            "CSS",
            "Front End Programmer",
            "Back End Programmer",
            "ASP.net",
            "Object Oriented Programming",
            "Fluid Dynamics",
            "Heat Transfer",
            "Electical Engineering",
            "Software Engineering",
            "Civil Engineering",
            "Industrial Engineering",
            "Nuclear Engineering",
            "Environmental Engineering",
            "Office Applications",
            "Acting ",
            "Modeling",
            "Production Skills",
            "Video Skills",
            "Creativity ",
            "Organizational Skills",
            "Internet",
            "Web Analytics",
            "Quicktime",
            "Financial Statement Analysis",
            "Styling Experience",
            "Merchandise Experience",
            "Fabric Design",
            "Sewing",
            "Algorithm Design Experience",
            "Computer Science",
            "Math",
            "Calculus",
            ".NET",
            "GUI Development",
            "CSS",
            "Front End Programmer",
            "Back End Programmer",
            "ASP.net",
            "Object Oriented Programming",
            "Fluid Dynamics",
            "Heat Transfer",
            "Electical Engineering",
            "Software Engineering",
            "Civil Engineering",
            "Industrial Engineering",
            "Nuclear Engineering",
            "Environmental Engineering",
            "Office Applications",
            "Acting",
            "Modeling",
            "Production Skills",
            "Video Skills",
            "Creativity ",
            "Organizational Skills",
            "Internet",
            "Web Analytics",
            "Quicktime",
            "Financial Statement Analysis",
            "Styling Experience",
            "Merchandise Experience",
            "Fabric Design",
            "Sewing",
            "Sewing",
            "Objective Caml",
            "Visual C++.net",
            "Jscript"
        );


        //check for uniqe skill
        $uniqeArray = array();
        foreach ($skillsArray as $skill) {
            $skill = strtolower($skill);
            $skill = trim($skill);
            if (!in_array($skill, $uniqeArray)) {
                array_push($uniqeArray, $skill);
                $newSkill = new Skill();
                $newSkill->setTitle($skill);
                $manager->persist($newSkill);
            }
        }

        $manager->flush();
    }

}